Корректировка №1 кода по задаче о классе матрицы
viacheslav-konstantinov/made_2019_cpp pull request #2
Opened 2019-11-05 21:59 UTC by viacheslav-konstantinov

1) virtual ~Matrix(); -> ~Matrix();

2) int dim1, dim2;  ->  size_t dim1, dim2; 

3.0) У прокси класса описан конструктор и метод setDimension, который удаляет записанный массив и изменяет его размер:
Matrix::Array1D::Array1D(size_t d2)
{
    dim2 = d2;
    Array1 = new int [d2];
}
void Matrix::Array1D::setDimension(size_t d2)
{
    dim2 = d2;
    delete [] Array1;
    Array1 = new int [d2];
}

3.1) Конструктор класса Matrix переписан с использованием метода setDimension прокси-класса: 
Matrix::Matrix(size_t d1, size_t d2)
{
    dim1 = d1;
    ArrayMatrix = new Array1D [dim1]();
    for (size_t i = 0; i < d1; ++i)
        ArrayMatrix[i].setDimension(d2);
}

4) Переписаны деструкторы прокси-класса и класса Matrix:
~Array1D() { delete[] Array1;}
~Matrix() { delete[] ArrayMatrix; }

5) Переписан код перегрузки оператора =*:
Matrix& Matrix::operator *= (int multiplier)
{
    int currentValue;
    for(size_t i = 0; i < dim1; ++i)
    {
        for(size_t j = 0; j < ArrayMatrix[i].dim2; ++j)
        {
            currentValue = ArrayMatrix[i][j];
            currentValue *= multiplier;
            ArrayMatrix[i][j] = currentValue;
        }
    }
    return *this;
}

2019-11-06 12:43 UTC, smirnov-vs requested changes

2019-11-06 12:43 UTC, smirnov-vs commented on 04/main.cpp
> +void Matrix::Array1D::setDimension(size_t d2)
эту функцию лучше перенести в конструктор класса, чтобы было проще

2019-11-06 12:43 UTC, smirnov-vs commented on 04/main.cpp
> +    return *this;
этого не было, вызывало ub , остальное было ок

2019-11-06 12:43 UTC, smirnov-vs commented on 04/main.cpp
> +        ArrayMatrix[i].setDimension(d2);
тогда здесь не надо будет вызывать, можно будет пользоваться только конструктором

2019-11-07 09:01 UTC, viacheslav-konstantinov commented on 04/main.cpp
> +void Matrix::Array1D::setDimension(size_t d2)
Конструктор класса определён: он и метод setDimension выполняют одинаковые функции. 
Метод setDimension используется для того, чтобы в конструкторе класса Matrix в цикле установить размерность матрицы dim2. Как там можно обойтись без setDimension, я не могу понять.

2019-11-07 09:02 UTC, viacheslav-konstantinov commented on 04/main.cpp
> +        ArrayMatrix[i].setDimension(d2);
Не понимаю, как здесь можно обойтись только конструктором Array1D без метода setDimension

2019-11-07 09:03 UTC, viacheslav-konstantinov commented on 04/main.cpp
> +    return *this;
Хорошо, понял, спасибо!

2019-11-13 12:02 UTC, merged

2019-11-13 18:03 UTC, smirnov-vs commented
пока задачу не закрыли мержить её нельзя