Домашнее задание 5 Сериализатор
viacheslav-konstantinov/made_2019_cpp pull request #3
Opened 2019-11-13 11:58 UTC by viacheslav-konstantinov

2019-11-13 18:02 UTC, smirnov-vs requested changes

2019-11-13 18:02 UTC, smirnov-vs commented on 05/main.cpp
> +        Error process_(U& val, Args&&... args)
либо форвард, либо lvalue, выбираем что-то одно по смыслу

2019-11-13 18:02 UTC, smirnov-vs commented on 05/main.cpp
> +int getInStream<u_int64_t>(u_int64_t& val, std::istream& inStream)
это перегрузки функций, специализация тут не нужна

2019-11-13 18:02 UTC, smirnov-vs commented on 05/main.cpp
> +            return process_(args...);
дальше идут форвард ссылки, а тут почему то их нет, получается вся цепочка не работает

2019-11-13 18:02 UTC, smirnov-vs commented on 05/main.cpp
> +    catch(...)
а тут какое исключение ловим?

2019-11-13 18:02 UTC, smirnov-vs commented on 05/main.cpp
> +        return -1;
пусть возвращают enum, а то это магические числа

2019-11-13 18:02 UTC, smirnov-vs commented on 05/main.cpp
> +            int result = putOutStream(val, out_, Separator);
форвард потерялся

2019-11-19 21:05 UTC, viacheslav-konstantinov commented
Переписал код с учётом замечаний:
1) В методах operator() и process_  используются универсальные ссылки и forward;
2) getInStream и putOutStream выполнены без специализации и возвращают Error, а не int;
3) В getInStream для u_int64_t ловится исключение типа std::invalid_argument;
4) В process_  класса  Serializer:  
Error result = putOutStream(val, out_, Separator)  -> Error result = putOutStream(std::forward<U>(val), out_, Separator) 
5) В process_  класса Deserializer:
Error result = getInStream (Val, in_); -> Error result = getInStream (STD::forward<U>(val), in_);

2019-12-25 11:40 UTC, smirnov-vs approved these changes
привет!
хорошо, я зачел

2020-01-05 14:39 UTC, merged