ДЗ 6. Класс для работы с большими целыми числами
viacheslav-konstantinov/made_2019_cpp pull request #5
Opened 2019-12-18 10:07 UTC by viacheslav-konstantinov

Реализован класс для работы с большими целыми числами. 
Размер числа ограничен только размером памяти. 
Поддерживается семантика работы с обычным int:

BigInteger a = 1;
BigInteger b = a;
BigInteger c = a + b + 2;
Реализованы операторы вывода в поток, считывания из потока, сложения, вычитания,
умножения, деления, унарного минуса, инкремента и декремента, все операции сравнения. 

Разряды хранится в виде массива unsigned char фиксированной длины на куче.
При изменении числа перерасчитывается требуемая длина массива и перевыделятся 
память. В каждом разряде записано число от 0 до 99.

2019-12-25 11:46 UTC, smirnov-vs requested changes

2019-12-25 11:46 UTC, smirnov-vs commented on 06/main.cpp
> +#include <iostream>
почему всё в main?

2019-12-25 11:46 UTC, smirnov-vs commented on 06/main.cpp
> +        BigInteger(int&& inputInteger);
rvalue для int?
с какой целью?

2019-12-25 11:46 UTC, smirnov-vs commented on 06/main.cpp
> +    int buffer(std::forward<int>(other));
форвард инта, причем rvalue, нужно разобраться в теме

2019-12-25 11:46 UTC, smirnov-vs commented on 06/main.cpp
> +    // резервное копирование из other
оператор перемещения и копирование?

2019-12-25 11:46 UTC, smirnov-vs commented on 06/main.cpp
> +    *this = *this / other;
обычно работает наоборот, += не создает объекты, а + создает новый, менять не обязательно

2020-01-08 15:54 UTC, viacheslav-konstantinov commented
**Корректировки в коде**
1) В конструкторе перемещения `BigInteger::BigInteger(int&& other)` переменная `buffer` инициализируется без  `std::forward`:
 `int buffer(other);`
2) В операторе перемещения скорректировано условие проверки на перемещения объекта в самого себя:
```
    if(this == &other)
        return *this;
```

2020-01-10 10:40 UTC, smirnov-vs commented
привет!

нужно разобраться с rvalue-ссылками, исправить `int&&`, ответ 4 в корне неверный, никто так не делает, все реализуется без этой перегрузки, нужно ответить, почему в ней нет смысла

еще нужно разделить на файлы main.cpp, сделать BigInt подключаемым в main, это тема первых лекций
не очень понял текст ответа 3, как связаны фрагментация памяти и файлы кода?

в операторе _перемещения_ до сих пор происходит _копирование_, я не могу зачесть задачку, в которой почти ничего не исправлено, время еще есть

2020-01-11 13:01 UTC, viacheslav-konstantinov commented
**Внесённые изменения**
1) Исправил реализация оператора перемещения в `BigInteger`: теперь он состоит в проверке на перемещение в самого себя, удаления разрядов в том объекте, в который происходит перемещение, передачи указателя на разряды из перемещаемого объекта и сохранение информации и него и затем - "обнуления" перемещаемого объекта. 
```
BigInteger& BigInteger::operator=(BigInteger&& other)
{
    if(this == &other)
        return *this;

    // удаление разрядов текущего объекта
    delete[] digits_;

    // передача управления разрядами из other
    // и сохранение информации оттуда
    digits_      = other.digits_;
    digitLength_ = other.digitLength_;
    isNegative_  = other.isNegative_;

    // "обнуление" other
    other.digits_ = nullptr;
    other.isNegative_ = false;
    other.digitLength_ = 0;

    return *this;
}
```
2) Убрал конструктор копирования и пермещения с int && other. Если я правильно понял, то в них смысла нет по двум причинам. Во-первых, для встроенных типов пермещение = копирование, и, во-вторых, для инта в `BigInteger(2)` или `BigIntegerBigInteger = 2` получается константная ссылка и исользуются конструктор и метод с аругментом `const int& other`.
3) Класс BigInteger реализовал в виде заголовочного файла `BigInteger.hpp`.

2020-01-13 09:37 UTC, smirnov-vs requested changes

2020-01-13 09:37 UTC, smirnov-vs commented on 06/bigInteger.hpp
> +        BigInteger(const int& other);
так как `sizeof(int) <= sizeof(void*)`, ссылка на этот тип избыточна, можно просто по значению

2020-01-13 09:37 UTC, smirnov-vs commented on 06/bigInteger.hpp
> +}
реализация функций в хедере ведет к ошибкам линковки, исправляем дальше

2020-01-14 14:26 UTC, viacheslav-konstantinov commented
1) Разделил объявление и реализацию класса `BigInteger`: объявление - в `bigInteger.hpp`, реализация - в `bigInteger.cpp`. Соответствующим образом изменён `Makefile`;
2) Конструктор и `operator=` для `int` принимают число по константному значению:
```
        BigInteger(const int other);
        BigInteger& operator=(const int other);
```

2020-01-15 09:28 UTC, smirnov-vs approved these changes
хорошо, вопросов нет

2020-01-15 15:21 UTC, merged