ДЗ 7. Функция для форматирования строки
viacheslav-konstantinov/made_2019_cpp pull request #7
Opened 2019-12-18 10:17 UTC by viacheslav-konstantinov

Реализована функция pythonString для форматирования строки, которая поддерживает любой тип, который может быть выведен в поток вывода. Формат строки форматирования:

"{0} any text {1} {0}"

Номер в фигурных скобках - номер аргумента. Если аргументов меньше, чем число в скобках, и в случае прочих ошибок выбрасывается исключение std::runtime_error.

Пример:
auto text = format("{1}+{1} = {0}", 2, "one");
assert(text == "one+one = 2");

Фигурные скобки - зарезервированный символ, если встречаются вне контекста {n} выбрасывается исключение std::runtime_error

Функция релизована в заголовочном файле "pythonString.hpp".

2019-12-25 11:50 UTC, smirnov-vs requested changes

2019-12-25 11:50 UTC, smirnov-vs commented on 07/pythonString.hpp
> +std::string pythonString(std::string str = "", TArgs&&... args)
входная строка скопирована

2019-12-25 11:50 UTC, smirnov-vs commented on 07/pythonString.hpp
> +    if(!str.length())
`empty()`

2019-12-25 11:50 UTC, smirnov-vs commented on 07/pythonString.hpp
> +        std::string message = "Some of the provided arguments cannot be printed into std::cout.\n";
почему cout?

2019-12-25 11:50 UTC, smirnov-vs commented on 07/pythonString.hpp
> +    catch(const std::ios::failure& e)
когда выпадет такое исключение?

2019-12-25 11:50 UTC, smirnov-vs commented on 07/pythonString.hpp
> +                    break;
как-то сложно, если нашли первую скобку, тогда можно начать парсить число, функция парсинга, как видно в документации, возвращает указатель на первый символ после числа, если он не вторая скобка, значит проблема, ну и обработать это всё

2020-01-08 18:12 UTC, viacheslav-konstantinov commented
**Изменения в коде**
1) Изменил сигнатуру функции `pythonString`: теперь она принимает строку по ссылке:
```
template<typename ...TArgs>
std::string pythonString(std::string& str = "", TArgs&&... args)
```
2) Упростил алгоритм парсинга строки:
```
    std::string result = "";
    for(size_t idx = 0; idx < str.length(); )
    {
         //если встретилась открывающая скобка
        if(str.at(idx) == '{')
        {
            size_t  argIdx;
            size_t  pos = idx;     
            try
            {

                argIdx = std::stoi(str.substr(idx + 1), &pos);
                result = result + argsPrinted.at(argIdx);
                idx = idx + 1 + pos;
                
                if( str.at(idx) != '}')
                {
                    //после парсинга числа следующий за ним символ != }' => нарушение синтаксиса
                    std::string message = "Expected a closing brace at position " + std::to_string(idx) + ", ";
                    message = message + "but " + str.at(idx) + " instead.\n";
                    message = message + "Successfully passed part of the string:\n" + result;
                    throw std::runtime_error(message);
                }
                else
                {
                    ++idx;
                }

            }
            // далее - проверка исключений
...
        // если символ - ни открывающая, ни закрывающая скобка
        else if (str.at(idx)  != '}')
        {
            result += str.at(idx) ;
            ++idx;
        }
```
3) Изменил код в `*.cpp` - файлах в соотвествии с новой сигнатурой и алгоритмом парсинга

2020-01-10 10:42 UTC, smirnov-vs approved these changes
я зачел эту

2020-01-10 10:42 UTC, smirnov-vs commented on 07/pythonString.hpp
> +    catch(const std::ios::failure& e)
такое исключение никогда не выскочит, если не нашелся `<<` будет ошибка компиляции

2020-01-10 10:42 UTC, smirnov-vs commented on 07/pythonString.hpp
> +std::string pythonString(std::string& str = "", TArgs&&... args)
нет `const`

2020-01-15 15:22 UTC, merged