Домашнее задание 8. Класс Vector, Allocator и Iterator
viacheslav-konstantinov/made_2019_cpp pull request #8
Opened 2020-01-05 14:32 UTC by viacheslav-konstantinov

Реализован класс контейнера Vector аналогичный std::vector.
Поддерживаемые методы: operator[]; push_back, pop_back, empty, size, clear, begin, end, rbegin, cbegin, crbegin, cend, crend, rend, resize, reserve, capacity.
Для контейнера Vector реализованы классы аллокатора Allocator и итератора Iterator произвольного доступа для него.

2020-01-08 18:36 UTC, viacheslav-konstantinov commented
Просьба: если есть какие-то замечания по задаче, но нет времени на их исправления, дать обратную связь по недочётам и зачесть задачу в текущем виде.

2020-01-10 10:48 UTC, smirnov-vs requested changes
нужно поправить замечания, я все подробно описал

2020-01-10 10:48 UTC, smirnov-vs commented on 08/main.cpp
> +    pointer begin_ = nullptr; // указатель на начало аллоцированной памяти
аллокатор не хранит состояние, он отдает память пользователю, это такой интерфейс

2020-01-10 10:48 UTC, smirnov-vs commented on 08/main.cpp
> +            pointer result = new T[n];
метод `allocate` не вызывает конструкторы, только память выделяет

2020-01-10 10:48 UTC, smirnov-vs commented on 08/main.cpp
> +            std::memcpy(result, begin_, reserved*sizeof(T));
это нарушает семантику копирования c++

2020-01-10 10:48 UTC, smirnov-vs commented on 08/main.cpp
> +    : public std::iterator<std::forward_iterator_tag, T>
не та категория для итератора вектора, смена категории означает добавление нужных методов

2020-01-10 10:48 UTC, smirnov-vs commented on 08/main.cpp
> +    void push_back(value_type&& value)
этот метод должен перемещать, работает неверно

2020-01-10 10:48 UTC, smirnov-vs commented on 08/main.cpp
> +        return *const_iterator(begin_ + pos);
можно было и без итератора, оверхед только получился

2020-01-10 10:48 UTC, smirnov-vs commented on 08/main.cpp
> +int main()
надо разделить вектор с классами и тесты хотя бы на 2 файла

2020-01-10 10:48 UTC, smirnov-vs commented on 08/test1.cpp
> +class Allocator
копипасту убрать

2020-01-11 17:36 UTC, viacheslav-konstantinov commented
1) Реализацию классов `Allocator`, `Iterator`, `Vector` переместил в соотвествующие заголовочные файлы,  в `main.cpp` и тестах подключается `Vector.hpp`;
2) В классе `Allocator` метод `allocate` выделяет память через выделяет через `return (pointer) malloc(sizeof(value_type) * n)`, т. е. не вызывает конструкторы, и освобождается с помощью функции `free()`; 
3) Класс Allocator теперь **не хранит** состояния;
4) Для класса `Iterator` добавил конструктор без аргументов, постфиксный инкремент и перегрузку функции swap;
5) В классе `Vector` метод  `void push_back(value_type&& value)` теперь перемещает `value`, вызывая `alloc_.construct(buffer + used, std::move(value))`;
5) В классе `Vector` изменил реализацию методов push_back, reserve, resize в той части, что при увеличении выделенного участка памяти, текущие данные копируются в расширенный участок с помощью аллокатора  `alloc_.construct(buffer + idx, *(begin_ + idx))`;
6) В классе `Vector`  методы operator[] возврщают указатели в виде `*(begin_ + pos)`, а не итераторы.

2020-01-13 09:48 UTC, smirnov-vs requested changes

2020-01-13 09:48 UTC, smirnov-vs commented on 08/Iterator.hpp
> +    : public std::iterator<std::forward_iterator_tag, T>
форвард итератор не подходит для вектора, коллеги с курса алгоритмов или документация могут помочь с правильным решением

2020-01-13 09:48 UTC, smirnov-vs commented on 08/Vector.hpp
> +        pointer buffer = alloc_.allocate(reserved*2);
это копипаста, можно вынести в функцию

2020-01-13 09:48 UTC, smirnov-vs commented on 08/Vector.hpp
> +    void reserve(size_type count)
вот же похоже она, кстати

2020-01-14 14:44 UTC, viacheslav-konstantinov commented
1) Итератор указал `std::random_access_iterator_tag` (в документации на vector, [указано](http://www.cplusplus.com/reference/vector/vector/begin/), что итераторы имеют именно такой тип), реализовал соответствующие методы и функции в `Iterator.hpp`;
2) В классе `Vector.hpp` реализовал приватные методы `push_back_` и `resize_` и использовал их внутри соответствующих пубичных методов, чтобы не копипастить:
```
    void push_back_(value_type&& value);
    void resize_(size_type newSize, const value_type& value);
```

2020-01-15 09:29 UTC, smirnov-vs approved these changes
окей, зачтено

2020-01-15 15:20 UTC, merged