ДЗ 9 Реализация класса пула потоков ThreadPool
viacheslav-konstantinov/made_2019_cpp pull request #9
Opened 2020-01-06 22:24 UTC by viacheslav-konstantinov

Реализован класс пула потоков со следующим интерфейсом:

class ThreadPool
{
public:
    explicit ThreadPool(size_t poolSize);

    ThreadPool(const ThreadPool& other) = delete;
    ThreadPool(ThreadPool&& other) = delete; 
    ThreadPool& operator=(const ThreadPool& other) = delete;
    ThreadPool& operator=(ThreadPool&& other) = delete;

    template <class Func, class... Args>
    auto exec(Func func, Args... args) -> std::future<decltype(func(args...))>;
    bool isReady(); // выполнены ли все работы
    void printWorkerStates(); // текущий статус потоков в пуле и перечня работ

private:
    mutex m;
    condition_variable v;

    //перечень работ для выполнения
    deque<packaged_task<void()>> works;
    //потоки
    vector<future<void>> workingThreads;
    //статусы потоков
    vector<workerState> workerStatus;
    
    //функция, работающая в потоке
    void worker(size_t idx); 
};

2020-01-08 18:36 UTC, viacheslav-konstantinov commented
Просьба: если есть какие-то замечания по задаче, но нет времени на их исправления, дать обратную связь по недочётам и зачесть задачу в текущем виде.

2020-01-09 05:51 UTC, viacheslav-konstantinov commented
В реализации намеренно часто выполняется печать в `std::cout`, чтобы можно было отследить работу потоков и функций внутри них.

2020-01-10 10:53 UTC, smirnov-vs requested changes

2020-01-10 10:53 UTC, smirnov-vs commented on 09/ThreadPool.hpp
> +            cout << "Calling worker #" << workerIdx << endl;
надо поместить под `#ifdef DEBUG`
чтобы отключать в релизе

2020-01-10 10:53 UTC, smirnov-vs commented on 09/ThreadPool.hpp
> +            workingThreads.push_back(std::async(std::launch::async, [this, i]{ worker(i);}));
`async` слишком жирно, нужен `std::thread`

2020-01-10 10:53 UTC, smirnov-vs commented on 09/ThreadPool.hpp
> +            workerStatus[idx] = workerState::ready;
статусы я так понял только для дебага, тоже можно под `if`

2020-01-10 10:53 UTC, smirnov-vs commented on 09/ThreadPool.hpp
> +                works.push_back({});
переделать синхронизацию с `std::thread`

2020-01-11 20:20 UTC, viacheslav-konstantinov commented
1) Весь вывод на печать статусов в процессе работы потоков и функций внутри них убрал под `#ifdef DEBUG`. По умолчанию в компилируется релизная версия. Чтобы скомпилировать отладочный вариант с печатью статусов работы потоков, при запуске Makefile надо задать `RUN_MODE`: 
```
make RUN_MODE="-DDEBUG" <...>
```
2) Вместо `async` используется `std::thread`:
```
workingThreads.push_back(thread( [this, i]{ worker(i);}));
```
3) Для корректного удаления пула внутри него заведён массив `vector<bool> stopWorker` - переменная указывает, нужно ли завершить работу указанному потоку. Внтури потока выполняется цикл `while(!stopWorker.at(workerIdx))`. При инициализации пула все флаги в `stopWorker` устанавливаются в `false`:
```
stopWorker.resize(poolSize, false);
```
В деструкторе все флаги устанавливаются в `true`, дек работ заполяется "пустыми" работами по количеству потоков, запускаются, делается `join` к каждому. После этого массив потоков очищается.
```
workingThreads.clear();
```

2020-01-13 09:52 UTC, smirnov-vs requested changes

2020-01-13 09:52 UTC, smirnov-vs commented on 09/ThreadPool.hpp
> +        workingThreads.clear();
это лишняя строка, он и так очистится

2020-01-13 09:52 UTC, smirnov-vs commented on 09/ThreadPool.hpp
> +            // указываем потокам, чтобы они завершили свою работу
зачем это делать?
просто говорим потокам, что пора выходить и `join`

2020-01-13 09:52 UTC, smirnov-vs commented on 09/ThreadPool.hpp
> +        while(!stopWorker.at(workerIdx))
достаточно одной переменной на все потоки, концепция не подразумевает изменения количества потоков после конструирования, и переменная должна быть атомарной

2020-01-14 15:13 UTC, viacheslav-konstantinov commented
1) Вместо массива логических переменных `stopWorker` завёл 1 атомарную `stopPool_` - логическая переменная, указывающая на завершение работы пула. В неё записывается `false` в конструкторе и `true` - в деструкторе;
2) Изменил работу `worker` в части ожидания: теперь поток выходит из спящего режима, если дек работ `works_` не пуст или `stopPool_ ==  true`. 
Ожидание реализовано следующим образом:
```
                unique_lock<mutex> l(m_);
                if (works_.empty())
                {
                    //ждём нового задания или окончания работы пула
                    v_.wait(l, 
                    [&]
                    {
                        //записываем в doStop, чтобы далее не получать значение атомарной переменной
                        doStop = stopPool_.load(); 
                        return doStop || !works_.empty();
                    });
                }

                //если работа пула завершена, выходим из цикла
                if(doStop) 
                {
                    #ifdef DEBUG
                    cout << "Stopping worker #" << workerIdx << "..." << endl;
                    #endif
                    return;
                }
```
3) В предыдущей версии в `worker`, в `v_.wait(...)` в качестве предиката использовалась лямбда-функция, которая проверяла, не пуст ли дек работ `works_`. Поскольку проверялось _только это_ условие, в деструкторе приходилось запускать "пустые" работы, чтобы вывести потоки из спящего режима. В новой реализации функция предиката изменена, как показано в п.2, и пустые работы не запускаются. 
Деструтор пула имеет вид:
```
    ~ThreadPool() 
    {   
        //завершаем работу пула, уведовляем потоки
        stopPool_.store(true);   
        v_.notify_all();

        //дожидаемся завершения работы всех потоков
        for(size_t idx = 0; idx < workingThreads_.size(); ++idx)
        {
            workingThreads_[idx].join();
        }
    }
```

2020-01-15 09:30 UTC, smirnov-vs approved these changes
все окей

2020-01-15 15:19 UTC, merged